### ISSUE TITLE
Any specific reason to put "using <reference>" into namespaces?

### ISSUE THREAD

**Issue by adailsonfilho** [mderriey/tfs-webhooks#3]
Hi there again!

I've noticed that in all classes in the project the importing of references have been done inside the namespaces. After some fast research and reflection on life and this, hahaha, I realized that it might depend on the objective and practices of an developer / team and the project (obviously), despite many consider bad practice. So, any specific reason to put "using <reference>" into namespaces?

Thank you in advance,
\o

**Comment by mderriey** [comment]
There's no specific reason to explain why I put the `using` directives inside the `namespace` ones, it is just a style preference.
